// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkxWDQ0KTk8Jqe-R2RWFLbUrDJRqR1Pw',
    appId: '1:1013249757228:web:7021537be0a2ebbd548189',
    messagingSenderId: '1013249757228',
    projectId: 'spotify-app-6e4c8',
    authDomain: 'spotify-app-6e4c8.firebaseapp.com',
    storageBucket: 'spotify-app-6e4c8.appspot.com',
    measurementId: 'G-9N20KK5ZES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPihR_jiOt7h1DxAZ6SqHbVIaVQdpGPE',
    appId: '1:1013249757228:android:a64031b71cf6b68e548189',
    messagingSenderId: '1013249757228',
    projectId: 'spotify-app-6e4c8',
    storageBucket: 'spotify-app-6e4c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbasDCkjieK92lFLxxAtpY6biDpqQDQac',
    appId: '1:1013249757228:ios:bbf1109de38eed3d548189',
    messagingSenderId: '1013249757228',
    projectId: 'spotify-app-6e4c8',
    storageBucket: 'spotify-app-6e4c8.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbasDCkjieK92lFLxxAtpY6biDpqQDQac',
    appId: '1:1013249757228:ios:bbf1109de38eed3d548189',
    messagingSenderId: '1013249757228',
    projectId: 'spotify-app-6e4c8',
    storageBucket: 'spotify-app-6e4c8.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGkxWDQ0KTk8Jqe-R2RWFLbUrDJRqR1Pw',
    appId: '1:1013249757228:web:0672e29d780ff871548189',
    messagingSenderId: '1013249757228',
    projectId: 'spotify-app-6e4c8',
    authDomain: 'spotify-app-6e4c8.firebaseapp.com',
    storageBucket: 'spotify-app-6e4c8.appspot.com',
    measurementId: 'G-N65B3SGW7C',
  );

}